import type { SvelteKitPWAOptions } from "@vite-pwa/sveltekit";

/**
 * Navigations the service worker answers when the network fails (with the offline page): pages of
 * the app. It never touches `/api`, the guest pages (`/g`), `/login`, `/setup`, the offline page,
 * the service worker and the manifest, so downloads and everything public or token-based go
 * straight to the network. Only `GET` navigations are routed (workbox registers the route for GET).
 *
 * Workbox copies the source of this function into the service worker, so it must not reference
 * anything outside itself.
 */
export function isAppNavigation({
  request,
  url,
}: {
  request: Request;
  url: URL;
}): boolean {
  return (
    request.mode === "navigate" &&
    !/^\/(?:api|g|login|setup|offline|sw\.js|manifest\.webmanifest)(?:\/|$)/.test(
      url.pathname,
    )
  );
}

/**
 * Options of the `SvelteKitPWA` plugin in `vite.config.ts`. The generated service worker does this
 * and nothing else:
 *
 * - **Precache** the built static client files only: the hashed `_app/immutable` assets (scripts,
 *   styles, fonts), the icons and the favicon. No HTML, no JSON, no `_app/version.json`.
 * - **Navigations** to app pages go to the network and are never cached (`NetworkOnly`); if the
 *   network is down the precached offline page stands in. The offline page is the only HTML in the
 *   cache and holds no user data.
 * - **Everything else** (`/api`, `/g`, files, attachments, the `fetch()` calls of the app) is not
 *   handled at all: no route matches, so the browser talks to the server directly.
 *
 * A new version waits (`registerType: "prompt"`) until the person agrees to reload, see
 * `components/app/pwa-update.svelte`. The worker is generated by `vite build` only (`devOptions`),
 * and it is registered by that component, not by a script the plugin injects. The manifest is the
 * route `src/routes/manifest.webmanifest`. The workbox runtime is inlined so the worker is one file
 * (`scripts/move-service-worker.ts` moves it into the server build). `buildId` revises the offline
 * page, which the server renders and which links hashed assets, with every build.
 */
export function pwaOptions(buildId: string): Partial<SvelteKitPWAOptions> {
  return {
    // SvelteKit builds with relative asset paths (Vite's base is "./"), which the plugin would
    // take over: the worker would then be registered as "sw.js" relative to the current page.
    base: "/",
    scope: "/",
    registerType: "prompt",
    injectRegister: false,
    manifest: false,
    devOptions: { enabled: false },
    workbox: {
      globPatterns: [
        "client/_app/immutable/**/*.{js,css,woff2}",
        "client/icons/*.png",
        "client/favicon.svg",
      ],
      globIgnores: ["server/**", "prerendered/**"],
      // An (empty) prefix map keeps the SvelteKit integration from adding its default patterns for
      // prerendered pages and web manifests: this app has none, and each would warn at every build.
      modifyURLPrefix: {},
      additionalManifestEntries: [{ url: "/offline", revision: buildId }],
      // The plugin would register a navigation route that answers every page from the precache.
      navigateFallback: undefined,
      cleanupOutdatedCaches: true,
      // A new worker still waits for the person's consent (no skipWaiting), but once active it
      // takes over the open pages, also those loaded before any worker existed, so that the
      // update prompt can reload them.
      clientsClaim: true,
      inlineWorkboxRuntime: true,
      runtimeCaching: [
        {
          urlPattern: isAppNavigation,
          handler: "NetworkOnly",
          options: { precacheFallback: { fallbackURL: "/offline" } },
        },
      ],
    },
  };
}
